name: Generate Kaggle Notebook

on: [pull_request,workflow_dispatch]

jobs:
  build-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.13.5
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      # Step 3: Install workflow tools
      - name: Install workflow tools
        run: |
          python -m pip install --upgrade pip
          pip install kaggle pipreqs jupytext nbformat kaggle            

      # Step 4: Generate requirements and install dependencies
      - name: Generate and install project dependencies
        run: |
          pipreqs ./src --force
          pip install -r requirements.txt

      # Step 5: Generate the notebook
      - name: Generate notebook
        run: python generate_notebook.py

      - name: Upload notebook as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: kaggle-notebook # A name for your artifact
          path: gai-vlm.ipynb    # The path to the notebook file to save

  deploy-to-kaggle:
    if: github.event_name == 'pull_request'
    needs: build-notebook
    runs-on: ubuntu-latest
    steps:
      - name: Download notebook artifact
        uses: actions/download-artifact@v4
        with:
            name: kaggle-notebook

      - name: Deploy to Kaggle
        env:
            KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
            KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: 
            export PATH=$PATH:~/.local/bin
            kaggle kernels push -p .